### ISSUE TITLE
Add "Powered by TDWG" to the footer

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#8]
@jmacklin would like TDWG to be acknowledged on our site in a similar style to the "Powered by GBIF" acknowledgement.

It would say "Powered by TDWG" with a link to TDWG's site.

I couldn't figure out how to implement this.

**Comment by MortenHofft** [comment]
You have full control over the footer, but currently that last line isn't configurable. Perhaps adding an accolades group in https://github.com/gbif/hp-canadian-biodiversity/blob/master/_data/footer.yml#L6. 

> ** PARTNERS **
> This site wouldn't be possible without ....
> * TDWG
> * The XYZ foundation

This issue is closely related to https://github.com/gbif/hosted-portals/issues/97

You could even add a link to a page about TDWG in the menu if you want to highlight the important work of TDWG?

**Comment by jocelynpender** [comment]
I've added TDWG as a partner in commit b0956b5995b47264adaf90388c54236acfc410f6
