### ISSUE TITLE
Data page is broken

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#9]
**Describe the bug**
On this page: https://hp-canadian-biodiversity.gbif-staging.org/data
I see a 404 error:
![image](https://user-images.githubusercontent.com/16246446/112663632-7572d880-8e2f-11eb-839e-3730e4455c26.png)

**To Reproduce**
1. Go to the data page
2. See error

**Expected behavior**
I expect to see the data page. It looks like the data page of the BISON hp is working just fine for me:
![image](https://user-images.githubusercontent.com/16246446/112663794-9e936900-8e2f-11eb-9802-7a5ca069d8d9.png)

**Additional context**
The data page _was_ working on our portal previously. What happened?

**Comment by MattBlissett** [comment]
Hi,

It looks like Morten moved the English pages to be under /en/, for issue #2, but didn't update the main navigation links.

I've done that (see https://github.com/gbif/hp-canadian-biodiversity/commit/0bb11d13da8ec1c16db92836bbceb303e3f92cf4#diff-f8949f06b04d9d8da89c490e107e04dba06c3e06fbb9000b46192062437ac187 ) and now the data page works completely.

This is strange, because I tried the French page too (and this didn't move), and it was also broken previously.

**Comment by jocelynpender** [comment]
Oooo awesome, thank you @MattBlissett !
